service: api-v2-custom-auth

licenseKey: ${ssm:/aws/reference/secretsmanager/serverless-framework-access-key}

custom:
  prune:
    automatic: true
    number: 1

provider:
  logRetentionInDays: 7
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  httpApi:
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunction
        enableSimpleResponses: true
        identitySource:
          - $request.header.Authorization
  name: aws
  runtime: nodejs20.x
  stage: dev
  tags:
    lumigo:auto-trace: 'true'

functions:
  getGreeting:
    handler: src/handler.default
    events:
      - httpApi:
          method: GET
          path: /greeting
          authorizer:
            name: customAuthorizer
  authorizerFunction:
    handler: src/authorizer.default

build:
  esbuild:
    bundle: true
    minify: true
    exclude:
      - '@aws-sdk/*'

package:
  individually: true

plugins:
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function


